### ISSUE TITLE
Python 3.7 compatibility

### ISSUE THREAD

**Issue by lgragert** [nmdp-bioinformatics/seq-ann#97]
python3 test_seqann.py
Traceback (most recent call last):
  File "test_seqann.py", line 1, in <module>
    from seqann import BioSeqAnn
  File "/usr/local/lib/python3.7/site-packages/seqann/__init__.py", line 25, in <module>
    from .sequence_annotation import BioSeqAnn
  File "/usr/local/lib/python3.7/site-packages/seqann/sequence_annotation.py", line 40, in <module>
    from seqann.models.annotation import Annotation
  File "/usr/local/lib/python3.7/site-packages/seqann/models/annotation.py", line 25, in <module>
    from seqann.models.base_model_ import Model
  File "/usr/local/lib/python3.7/site-packages/seqann/models/base_model_.py", line 27, in <module>
    from ..util import deserialize_model
  File "/usr/local/lib/python3.7/site-packages/seqann/util.py", line 28, in <module>
    from typing import GenericMeta
ImportError: cannot import name 'GenericMeta' from 'typing' (/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py)

Discussion of issue is here:
https://github.com/hsolbrig/PyShEx/issues/17

**Comment by rsajulga-nmdp** [comment]
I'm still having this issue in Python 3.7 when following the example in https://github.com/nmdp-bioinformatics/py-gfe
